import traceback
"""
Report Generation Node — formats the structured analysis into a polished
Markdown report and a structured JSON output.
"""
import json
import logging
from datetime import datetime
from langchain_core.messages import HumanMessage
from workflow.state import ResearchState
from services.llm import get_llm, extract_text

logger = logging.getLogger(__name__)


def _build_markdown_report(analysis: dict, company_name: str, objective: str) -> str:
    """
    Build a polished Markdown report from the structured analysis.
    """
    now = datetime.utcnow().strftime("%B %d, %Y")

    def safe_get(key: str, default="Not available") -> str:
        val = analysis.get(key, default)
        if isinstance(val, list):
            return "\n".join(f"- {item}" for item in val) if val else f"- {default}"
        return val if val and val != "Unknown" else default

    def safe_list(key: str) -> list:
        val = analysis.get(key, [])
        return val if isinstance(val, list) else [val]

    discovery_qs = safe_list("discovery_questions")
    unknowns = safe_list("unknowns")
    sources = safe_list("sources")

    report = f"""# Research Briefing: {company_name}

> **Generated:** {now}  
> **Objective:** {objective}  
> **Quality Score:** {analysis.get('_quality_score', 'N/A')}

---

## 🏢 Company Overview

{safe_get('company_overview')}

---

## 📦 Products & Services

{safe_get('products_services')}

---

## 🎯 Target Customers

{safe_get('target_customers')}

---

## 📡 Business Signals

{safe_get('business_signals')}

---

## ⚠️ Risks & Challenges

{safe_get('risks_challenges')}

---

## ❓ Suggested Discovery Questions

{chr(10).join(f'{i+1}. {q}' for i, q in enumerate(discovery_qs))}

---

## 📨 Suggested Outreach Strategy

{safe_get('outreach_strategy')}

---

## 🔍 Unknowns & Gaps

{chr(10).join(f'- {u}' for u in unknowns)}

---

## 🔗 Sources

{chr(10).join(f'- {s}' for s in sources)}

---
*This briefing was generated by Insight AI.*
"""
    return report


async def report_gen_node(state: ResearchState) -> dict:
    """
    Generates the final polished report from the analysis.
    Also asks the LLM to enhance/polish the report.
    Returns: { report_markdown, report_json, status, current_node }
    """
    logger.info(f"[report_gen] Generating final report for {state['company_name']}")

    analysis = state.get("analysis", {})
    if not analysis:
        logger.warning("[report_gen] Empty analysis — generating minimal report")
        analysis = {
            "company_overview": f"Research for {state['company_name']} could not be fully completed.",
            "products_services": "Insufficient data collected.",
            "target_customers": "Unknown",
            "business_signals": "Unknown",
            "risks_challenges": "Unknown",
            "discovery_questions": ["What are your main business challenges?", "What does success look like for you?"],
            "outreach_strategy": "Schedule a discovery call to learn more.",
            "unknowns": ["Most information was unavailable"],
            "sources": [],
        }

    # Add quality score to analysis for display
    analysis["_quality_score"] = f"{state.get('quality_score', 0.0):.0%}"

    # Build the base report
    base_report = _build_markdown_report(analysis, state["company_name"], state["objective"])

    # Use LLM to polish the report for clarity and professionalism
    llm = get_llm()

    try:
        polish_prompt = f"""You are a professional sales intelligence writer. Polish and enhance the following research report for maximum clarity, professionalism, and sales usefulness.

Company: {state['company_name']}
Research Objective: {state['objective']}

Original Report:
{base_report}

Instructions:
- Preserve ALL sections and headers exactly as they appear
- Make language more crisp, professional, and actionable
- Add any obvious insights that would help a sales professional
- Keep the same Markdown format
- Do NOT add placeholder text or make things up
- Return the complete polished report in Markdown"""

        response = await llm.ainvoke([HumanMessage(content=polish_prompt)])
        final_markdown = extract_text(response)

        # If LLM returned something much shorter than expected, use original
        if len(final_markdown) < len(base_report) * 0.5:
            logger.warning("[report_gen] LLM polish returned too-short result, using base")
            final_markdown = base_report

    except Exception as e:
        logger.warning(f"[report_gen] Polish failed, using base report: {e}")
        final_markdown = base_report

    # Build structured JSON report
    report_json = {
        "company_name": state["company_name"],
        "website": state["website"],
        "objective": state["objective"],
        "sections": {
            "company_overview": analysis.get("company_overview", ""),
            "products_services": analysis.get("products_services", ""),
            "target_customers": analysis.get("target_customers", ""),
            "business_signals": analysis.get("business_signals", ""),
            "risks_challenges": analysis.get("risks_challenges", ""),
            "discovery_questions": analysis.get("discovery_questions", []),
            "outreach_strategy": analysis.get("outreach_strategy", ""),
            "unknowns": analysis.get("unknowns", []),
            "sources": analysis.get("sources", []),
        },
        "metadata": {
            "quality_score": state.get("quality_score", 0.0),
            "retry_count": state.get("retry_count", 0),
            "generated_at": datetime.utcnow().isoformat(),
        }
    }

    logger.info("[report_gen] Report generation complete")

    return {
        "report_markdown": final_markdown,
        "report_json": json.dumps(report_json, ensure_ascii=False),
        "status": "completed",
        "current_node": "report_gen",
        "error": None,
    }
